/**
 * CinematicHeroVideo — generated by the gemini-cinematic-web skill.
 *
 * A background *layer* you drop into an existing hero. It:
 *  - server-renders a responsive poster <picture> (the LCP element) with an inline blur placeholder
 *  - mounts the <video> only after the page has loaded and the browser is idle
 *  - never downloads video for prefers-reduced-motion, Save-Data or 2G users (poster only)
 *  - pauses when off-screen or the tab is hidden, and exposes an accessible pause/play control
 *  - reads a static manifest produced at build time, so regenerating the video needs no code change
 *
 * Parent requirements: position: relative; isolation: isolate; overflow: hidden
 * (Tailwind: "relative isolate overflow-hidden"). Or use <CinematicHeroSection>.
 */
import { useCallback, useEffect, useRef, useState, type CSSProperties, type ReactNode } from "react";
import defaultManifest from "./hero-video.manifest.json";
import styles from "./CinematicHeroVideo.module.css";

type Source = { src: string; type: string; width: number; height: number; bytes?: number };
type Poster = { src: string; type: string; width: number; height: number };
export type HeroVideoManifest = {
  sources: { desktop?: Source[]; mobile?: Source[] };
  posters: { desktop?: Poster[]; mobile?: Poster[] };
  placeholder?: string | null;
  focal?: { x: number; y: number };
  width?: number;
  height?: number;
};

export type CinematicHeroVideoProps = {
  manifest?: HeroVideoManifest;
  /** Where the hero text sits; shapes the readability scrim. */
  scrim?: "center" | "left" | "right" | "bottom" | "none";
  /** Any CSS color. Defaults to the site's --background token, then near-black. */
  scrimColor?: string;
  /** 0–1. Raise for light footage or thin display type. */
  scrimOpacity?: number;
  /** "idle" (default, best for LCP/INP), "eager" (right after hydration), or "visible". */
  loadStrategy?: "idle" | "eager" | "visible";
  showControl?: boolean;
  controlLabels?: { play: string; pause: string };
  className?: string;
};

const MOBILE_QUERY = "(max-aspect-ratio: 3/4)";

function srcSet(list: Poster[] | undefined, type: string) {
  return (list || []).filter((p) => p.type === type).map((p) => `${p.src} ${p.width}w`).join(", ");
}

function motionAllowed() {
  if (typeof window === "undefined") return false;
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return false;
  const conn = (navigator as Navigator & { connection?: { saveData?: boolean; effectiveType?: string } }).connection;
  if (conn?.saveData) return false;
  if (conn?.effectiveType && /(^|-)2g$/.test(conn.effectiveType)) return false;
  return true;
}

export default function CinematicHeroVideo({
  manifest = defaultManifest as unknown as HeroVideoManifest,
  scrim = "center",
  scrimColor,
  scrimOpacity = 0.55,
  loadStrategy = "idle",
  showControl = true,
  controlLabels = { play: "Play background video", pause: "Pause background video" },
  className,
}: CinematicHeroVideoProps) {
  const layerRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [shouldLoad, setShouldLoad] = useState(false);
  const [ready, setReady] = useState(false);
  const [paused, setPaused] = useState(false);
  const [userPaused, setUserPaused] = useState(false);
  const [sources, setSources] = useState<Source[]>([]);

  const hasVideo = Boolean(manifest?.sources?.desktop?.length);
  const desktopPosters = manifest?.posters?.desktop || [];
  const mobilePosters = manifest?.posters?.mobile || [];
  const fallback = desktopPosters.find((p) => p.type === "image/jpeg") || desktopPosters[0];

  const pickSources = useCallback(() => {
    const mobile = window.matchMedia(MOBILE_QUERY).matches && manifest.sources.mobile?.length;
    return (mobile ? manifest.sources.mobile : manifest.sources.desktop) || [];
  }, [manifest]);

  // Decide whether and when to fetch the video. Nothing here runs during SSR.
  useEffect(() => {
    if (!hasVideo || !motionAllowed()) { setPaused(true); return; }
    let cancelled = false;
    let idleId: number | undefined;
    let io: IntersectionObserver | undefined;
    const start = () => { if (!cancelled) { setSources(pickSources()); setShouldLoad(true); } };
    const whenIdle = () => {
      const ric = (window as Window & { requestIdleCallback?: (cb: () => void, o?: { timeout: number }) => number }).requestIdleCallback;
      idleId = ric ? ric(start, { timeout: 2000 }) : window.setTimeout(start, 300);
    };
    if (loadStrategy === "eager") start();
    else if (loadStrategy === "visible" && layerRef.current) {
      io = new IntersectionObserver((e) => { if (e[0]?.isIntersecting) { io?.disconnect(); whenIdle(); } });
      io.observe(layerRef.current);
    } else if (document.readyState === "complete") whenIdle();
    else window.addEventListener("load", whenIdle, { once: true });
    return () => { cancelled = true; io?.disconnect(); window.removeEventListener("load", whenIdle); if (idleId) (window.cancelIdleCallback || clearTimeout)(idleId); };
  }, [hasVideo, loadStrategy, pickSources]);

  // Play only while visible and the tab is active; respect the user's pause choice.
  useEffect(() => {
    const v = videoRef.current;
    if (!shouldLoad || !v || !layerRef.current) return;
    let visible = true;
    const sync = () => {
      if (visible && !document.hidden && !userPaused) v.play().catch(() => setPaused(true));
      else v.pause();
    };
    const io = new IntersectionObserver((e) => { visible = Boolean(e[0]?.isIntersecting); sync(); }, { threshold: 0.1 });
    io.observe(layerRef.current);
    document.addEventListener("visibilitychange", sync);
    sync();
    return () => { io.disconnect(); document.removeEventListener("visibilitychange", sync); };
  }, [shouldLoad, userPaused]);

  const toggle = () => {
    if (!shouldLoad) { setSources(pickSources()); setShouldLoad(true); setUserPaused(false); return; } // opt-in for reduced-motion users
    setUserPaused((p) => !p);
  };

  if (!hasVideo && !fallback) return null;

  const focal = manifest.focal || { x: 0.5, y: 0.5 };
  const vars = {
    "--cch-focal-x": `${focal.x * 100}%`,
    "--cch-focal-y": `${focal.y * 100}%`,
    ...(scrimColor ? { "--cch-scrim-color": scrimColor } : {}),
    "--cch-scrim-opacity": String(scrimOpacity),
  } as CSSProperties;

  return (
    <>
      <div ref={layerRef} className={[styles["layer"], className].filter(Boolean).join(" ")} style={vars} data-scrim={scrim}>
        <div className={styles["media"]} aria-hidden="true">
          {fallback && (
            <picture>
              {mobilePosters.length > 0 && <source media={MOBILE_QUERY} type="image/webp" srcSet={srcSet(mobilePosters, "image/webp")} sizes="100vw" />}
              {mobilePosters.length > 0 && <source media={MOBILE_QUERY} type="image/jpeg" srcSet={srcSet(mobilePosters, "image/jpeg")} sizes="100vw" />}
              <source type="image/webp" srcSet={srcSet(desktopPosters, "image/webp")} sizes="100vw" />
              {/* eslint-disable-next-line @next/next/no-img-element -- pre-optimized responsive poster; this is the LCP image */}
              <img
                className={styles["poster"]}
                src={fallback.src}
                srcSet={srcSet(desktopPosters, "image/jpeg")}
                sizes="100vw"
                width={manifest.width || fallback.width}
                height={manifest.height || fallback.height}
                alt=""
                decoding="async"
                fetchPriority="high"
                style={manifest.placeholder ? { backgroundImage: `url(${manifest.placeholder})`, backgroundSize: "cover" } : undefined}
              />
            </picture>
          )}
          {shouldLoad && (
            <video
              ref={videoRef}
              className={styles["video"]}
              data-ready={ready}
              muted
              loop
              playsInline
              autoPlay={!userPaused}
              preload="auto"
              disablePictureInPicture
              disableRemotePlayback
              tabIndex={-1}
              onPlaying={() => { setReady(true); setPaused(false); }}
              onPause={() => setPaused(true)}
              onError={() => setShouldLoad(false)}
            >
              {sources.map((s) => <source key={s.src} src={s.src} type={s.type} />)}
            </video>
          )}
        </div>
        {scrim !== "none" && <div className={styles["scrim"]} aria-hidden="true" />}
      </div>
      {showControl && hasVideo && (
        <button type="button" className={styles["control"]} onClick={toggle} aria-pressed={!paused} aria-label={paused ? controlLabels.play : controlLabels.pause} title={paused ? controlLabels.play : controlLabels.pause}>
          {paused ? (
            <svg viewBox="0 0 16 16" width="14" height="14" aria-hidden="true"><path d="M4 2.5v11l9-5.5z" fill="currentColor" /></svg>
          ) : (
            <svg viewBox="0 0 16 16" width="14" height="14" aria-hidden="true"><path d="M4 2.5h3v11H4zM9 2.5h3v11H9z" fill="currentColor" /></svg>
          )}
        </button>
      )}
    </>
  );
}

/** Convenience wrapper for sites that have no hero yet. Prefer the layer for existing heroes. */
export function CinematicHeroSection({ children, className, contentClassName, ...videoProps }: CinematicHeroVideoProps & { children?: ReactNode; contentClassName?: string }) {
  return (
    <section className={[styles["host"], className].filter(Boolean).join(" ")}>
      <CinematicHeroVideo {...videoProps} />
      <div className={[styles["content"], contentClassName].filter(Boolean).join(" ")}>{children}</div>
    </section>
  );
}
