/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiByokKeysRouteImport } from './routes/api/byok-keys'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiPublishRouteImport } from './routes/api/publish'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiVercelRouteImport } from './routes/api/vercel'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiByokKeysProviderRouteImport } from './routes/api/byok-keys.$provider'
import { Route as ApiPublishStatusRouteImport } from './routes/api/publish/status'
import { Route as ApiUploadsIdRouteImport } from './routes/api/uploads.$id'
import { Route as ApiVercelStatusRouteImport } from './routes/api/vercel/status'
import { Route as ApiWebhooksDodoRouteImport } from './routes/api/webhooks/dodo'
import { Route as ApiVercelOauthCallbackRouteImport } from './routes/api/vercel/oauth/callback'
import { Route as ApiVercelOauthStartRouteImport } from './routes/api/vercel/oauth/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiByokKeysRoute = ApiByokKeysRouteImport.update({
  id: '/api/byok-keys',
  path: '/api/byok-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVercelRoute = ApiVercelRouteImport.update({
  id: '/api/vercel',
  path: '/api/vercel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiByokKeysProviderRoute = ApiByokKeysProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => ApiByokKeysRoute,
} as any)
const ApiPublishStatusRoute = ApiPublishStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiPublishRoute,
} as any)
const ApiUploadsIdRoute = ApiUploadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const ApiVercelStatusRoute = ApiVercelStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiVercelRoute,
} as any)
const ApiWebhooksDodoRoute = ApiWebhooksDodoRouteImport.update({
  id: '/api/webhooks/dodo',
  path: '/api/webhooks/dodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVercelOauthCallbackRoute = ApiVercelOauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => ApiVercelRoute,
} as any)
const ApiVercelOauthStartRoute = ApiVercelOauthStartRouteImport.update({
  id: '/oauth/start',
  path: '/oauth/start',
  getParentRoute: () => ApiVercelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/api/byok-keys': typeof ApiByokKeysRouteWithChildren
  '/api/content': typeof ApiContentRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/me': typeof ApiMeRoute
  '/api/publish': typeof ApiPublishRouteWithChildren
  '/api/reset': typeof ApiResetRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/vercel': typeof ApiVercelRouteWithChildren
  '/api/waitlist': typeof ApiWaitlistRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/byok-keys/$provider': typeof ApiByokKeysProviderRoute
  '/api/publish/status': typeof ApiPublishStatusRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/api/vercel/status': typeof ApiVercelStatusRoute
  '/api/webhooks/dodo': typeof ApiWebhooksDodoRoute
  '/api/vercel/oauth/callback': typeof ApiVercelOauthCallbackRoute
  '/api/vercel/oauth/start': typeof ApiVercelOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/api/byok-keys': typeof ApiByokKeysRouteWithChildren
  '/api/content': typeof ApiContentRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/me': typeof ApiMeRoute
  '/api/publish': typeof ApiPublishRouteWithChildren
  '/api/reset': typeof ApiResetRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/vercel': typeof ApiVercelRouteWithChildren
  '/api/waitlist': typeof ApiWaitlistRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/byok-keys/$provider': typeof ApiByokKeysProviderRoute
  '/api/publish/status': typeof ApiPublishStatusRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/api/vercel/status': typeof ApiVercelStatusRoute
  '/api/webhooks/dodo': typeof ApiWebhooksDodoRoute
  '/api/vercel/oauth/callback': typeof ApiVercelOauthCallbackRoute
  '/api/vercel/oauth/start': typeof ApiVercelOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/api/byok-keys': typeof ApiByokKeysRouteWithChildren
  '/api/content': typeof ApiContentRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/me': typeof ApiMeRoute
  '/api/publish': typeof ApiPublishRouteWithChildren
  '/api/reset': typeof ApiResetRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/vercel': typeof ApiVercelRouteWithChildren
  '/api/waitlist': typeof ApiWaitlistRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/byok-keys/$provider': typeof ApiByokKeysProviderRoute
  '/api/publish/status': typeof ApiPublishStatusRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/api/vercel/status': typeof ApiVercelStatusRoute
  '/api/webhooks/dodo': typeof ApiWebhooksDodoRoute
  '/api/vercel/oauth/callback': typeof ApiVercelOauthCallbackRoute
  '/api/vercel/oauth/start': typeof ApiVercelOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/studio'
    | '/api/byok-keys'
    | '/api/content'
    | '/api/generate'
    | '/api/me'
    | '/api/publish'
    | '/api/reset'
    | '/api/uploads'
    | '/api/vercel'
    | '/api/waitlist'
    | '/api/billing/checkout'
    | '/api/byok-keys/$provider'
    | '/api/publish/status'
    | '/api/uploads/$id'
    | '/api/vercel/status'
    | '/api/webhooks/dodo'
    | '/api/vercel/oauth/callback'
    | '/api/vercel/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/studio'
    | '/api/byok-keys'
    | '/api/content'
    | '/api/generate'
    | '/api/me'
    | '/api/publish'
    | '/api/reset'
    | '/api/uploads'
    | '/api/vercel'
    | '/api/waitlist'
    | '/api/billing/checkout'
    | '/api/byok-keys/$provider'
    | '/api/publish/status'
    | '/api/uploads/$id'
    | '/api/vercel/status'
    | '/api/webhooks/dodo'
    | '/api/vercel/oauth/callback'
    | '/api/vercel/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/studio'
    | '/api/byok-keys'
    | '/api/content'
    | '/api/generate'
    | '/api/me'
    | '/api/publish'
    | '/api/reset'
    | '/api/uploads'
    | '/api/vercel'
    | '/api/waitlist'
    | '/api/billing/checkout'
    | '/api/byok-keys/$provider'
    | '/api/publish/status'
    | '/api/uploads/$id'
    | '/api/vercel/status'
    | '/api/webhooks/dodo'
    | '/api/vercel/oauth/callback'
    | '/api/vercel/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  ApiByokKeysRoute: typeof ApiByokKeysRouteWithChildren
  ApiContentRoute: typeof ApiContentRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiPublishRoute: typeof ApiPublishRouteWithChildren
  ApiResetRoute: typeof ApiResetRoute
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ApiVercelRoute: typeof ApiVercelRouteWithChildren
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiWebhooksDodoRoute: typeof ApiWebhooksDodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/byok-keys': {
      id: '/api/byok-keys'
      path: '/api/byok-keys'
      fullPath: '/api/byok-keys'
      preLoaderRoute: typeof ApiByokKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vercel': {
      id: '/api/vercel'
      path: '/api/vercel'
      fullPath: '/api/vercel'
      preLoaderRoute: typeof ApiVercelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/byok-keys/$provider': {
      id: '/api/byok-keys/$provider'
      path: '/$provider'
      fullPath: '/api/byok-keys/$provider'
      preLoaderRoute: typeof ApiByokKeysProviderRouteImport
      parentRoute: typeof ApiByokKeysRoute
    }
    '/api/publish/status': {
      id: '/api/publish/status'
      path: '/status'
      fullPath: '/api/publish/status'
      preLoaderRoute: typeof ApiPublishStatusRouteImport
      parentRoute: typeof ApiPublishRoute
    }
    '/api/uploads/$id': {
      id: '/api/uploads/$id'
      path: '/$id'
      fullPath: '/api/uploads/$id'
      preLoaderRoute: typeof ApiUploadsIdRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/api/vercel/status': {
      id: '/api/vercel/status'
      path: '/status'
      fullPath: '/api/vercel/status'
      preLoaderRoute: typeof ApiVercelStatusRouteImport
      parentRoute: typeof ApiVercelRoute
    }
    '/api/webhooks/dodo': {
      id: '/api/webhooks/dodo'
      path: '/api/webhooks/dodo'
      fullPath: '/api/webhooks/dodo'
      preLoaderRoute: typeof ApiWebhooksDodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vercel/oauth/callback': {
      id: '/api/vercel/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/api/vercel/oauth/callback'
      preLoaderRoute: typeof ApiVercelOauthCallbackRouteImport
      parentRoute: typeof ApiVercelRoute
    }
    '/api/vercel/oauth/start': {
      id: '/api/vercel/oauth/start'
      path: '/oauth/start'
      fullPath: '/api/vercel/oauth/start'
      preLoaderRoute: typeof ApiVercelOauthStartRouteImport
      parentRoute: typeof ApiVercelRoute
    }
  }
}

interface ApiByokKeysRouteChildren {
  ApiByokKeysProviderRoute: typeof ApiByokKeysProviderRoute
}

const ApiByokKeysRouteChildren: ApiByokKeysRouteChildren = {
  ApiByokKeysProviderRoute: ApiByokKeysProviderRoute,
}

const ApiByokKeysRouteWithChildren = ApiByokKeysRoute._addFileChildren(
  ApiByokKeysRouteChildren,
)

interface ApiPublishRouteChildren {
  ApiPublishStatusRoute: typeof ApiPublishStatusRoute
}

const ApiPublishRouteChildren: ApiPublishRouteChildren = {
  ApiPublishStatusRoute: ApiPublishStatusRoute,
}

const ApiPublishRouteWithChildren = ApiPublishRoute._addFileChildren(
  ApiPublishRouteChildren,
)

interface ApiUploadsRouteChildren {
  ApiUploadsIdRoute: typeof ApiUploadsIdRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsIdRoute: ApiUploadsIdRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

interface ApiVercelRouteChildren {
  ApiVercelStatusRoute: typeof ApiVercelStatusRoute
  ApiVercelOauthCallbackRoute: typeof ApiVercelOauthCallbackRoute
  ApiVercelOauthStartRoute: typeof ApiVercelOauthStartRoute
}

const ApiVercelRouteChildren: ApiVercelRouteChildren = {
  ApiVercelStatusRoute: ApiVercelStatusRoute,
  ApiVercelOauthCallbackRoute: ApiVercelOauthCallbackRoute,
  ApiVercelOauthStartRoute: ApiVercelOauthStartRoute,
}

const ApiVercelRouteWithChildren = ApiVercelRoute._addFileChildren(
  ApiVercelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  ApiByokKeysRoute: ApiByokKeysRouteWithChildren,
  ApiContentRoute: ApiContentRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiMeRoute: ApiMeRoute,
  ApiPublishRoute: ApiPublishRouteWithChildren,
  ApiResetRoute: ApiResetRoute,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ApiVercelRoute: ApiVercelRouteWithChildren,
  ApiWaitlistRoute: ApiWaitlistRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiWebhooksDodoRoute: ApiWebhooksDodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
