/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiUploadsIdRouteImport } from './routes/api/uploads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIdRoute = ApiUploadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUploadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/content': typeof ApiContentRoute
  '/api/me': typeof ApiMeRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/uploads/$id': typeof ApiUploadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/content': typeof ApiContentRoute
  '/api/me': typeof ApiMeRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/uploads/$id': typeof ApiUploadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/content': typeof ApiContentRoute
  '/api/me': typeof ApiMeRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/uploads/$id': typeof ApiUploadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/api/content'
    | '/api/me'
    | '/api/uploads'
    | '/api/uploads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio'
    | '/api/content'
    | '/api/me'
    | '/api/uploads'
    | '/api/uploads/$id'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/api/content'
    | '/api/me'
    | '/api/uploads'
    | '/api/uploads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  ApiContentRoute: typeof ApiContentRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$id': {
      id: '/api/uploads/$id'
      path: '/$id'
      fullPath: '/api/uploads/$id'
      preLoaderRoute: typeof ApiUploadsIdRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
  }
}

interface ApiUploadsRouteChildren {
  ApiUploadsIdRoute: typeof ApiUploadsIdRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsIdRoute: ApiUploadsIdRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  ApiContentRoute: ApiContentRoute,
  ApiMeRoute: ApiMeRoute,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
